package db

import (
	"os"
	"testing"
)

func TestStore_CreateAndGet(t *testing.T) {
	dbPath := "test_urls.db"
	defer os.Remove(dbPath)

	store, err := NewStore(dbPath)
	if err != nil {
		t.Fatalf("failed to create store: %v", err)
	}
	defer store.Close()

	// Test 1: Create URL with custom slug
	slug, err := store.CreateURL("https://example.com", "custom-slug")
	if err != nil {
		t.Fatalf("failed to create URL: %v", err)
	}
	if slug != "custom-slug" {
		t.Errorf("expected slug 'custom-slug', got '%s'", slug)
	}

	// Test 2: Get and increment hits
	target, hits, err := store.GetAndIncrementHits("custom-slug")
	if err != nil {
		t.Fatalf("failed to get and increment: %v", err)
	}
	if target != "https://example.com" || hits != 1 {
		t.Errorf("unexpected target or hits: target=%s, hits=%d", target, hits)
	}

	// Test 3: Get stats
	stats, err := store.GetStats("custom-slug")
	if err != nil {
		t.Fatalf("failed to get stats: %v", err)
	}
	if stats.Hits != 1 || stats.TargetURL != "https://example.com" {
		t.Errorf("unexpected stats: %+v", stats)
	}

	// Test 4: Delete URL
	if err := store.DeleteURL("custom-slug"); err != nil {
		t.Fatalf("failed to delete URL: %v", err)
	}
	_, _, err = store.GetAndIncrementHits("custom-slug")
	if err == nil {
		t.Fatal("expected error after delete, got nil")
	}
}

func TestStore_AutoGeneratedSlug(t *testing.T) {
	dbPath := "test_autourl.db"
	defer os.Remove(dbPath)

	store, err := NewStore(dbPath)
	if err != nil {
		t.Fatalf("failed to create store: %v", err)
	}
	defer store.Close()

	slug, err := store.CreateURL("https://example.org", "")
	if err != nil {
		t.Fatalf("failed to create URL: %v", err)
	}
	if slug == "" {
		t.Errorf("expected generated slug, got empty")
	}
}
